// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {domain} from '../models';

export function CancelNativeRegion():Promise<void>;

export function CancelRegion():Promise<void>;

export function CaptureNow():Promise<void>;

export function ConfirmNativeRegion(arg1:main.CaptureResult):Promise<void>;

export function ConfirmRegion(arg1:main.CaptureResult):Promise<void>;

export function GetConfig():Promise<domain.AppConfig>;

export function QuitApp():Promise<void>;

export function RetryRegisterHotkey():Promise<void>;

export function SaveConfig(arg1:domain.AppConfig):Promise<void>;

export function ShowWindow():Promise<void>;

export function TestConnection(arg1:domain.S3Config):Promise<void>;
