// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelNativeRegion() {
  return window['go']['main']['App']['CancelNativeRegion']();
}

export function CancelRegion() {
  return window['go']['main']['App']['CancelRegion']();
}

export function CaptureNow() {
  return window['go']['main']['App']['CaptureNow']();
}

export function ConfirmNativeRegion(arg1) {
  return window['go']['main']['App']['ConfirmNativeRegion'](arg1);
}

export function ConfirmRegion(arg1) {
  return window['go']['main']['App']['ConfirmRegion'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RetryRegisterHotkey() {
  return window['go']['main']['App']['RetryRegisterHotkey']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
